version: '1'

services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - "${MYSQL_PORT_HOST}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: quiz_db
    volumes:
      - ./database/init_dummy_db.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
